name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/Checkout@v2
    - name: Format
      uses: JohnnyMorganz/stylua-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --check .
    - name: Run luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        annotate: warning
        args: --no-color
