name: Package and release
on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          # this fetches everything, we'll need it to generate changelogs
          fetch-depth: 0

      - name: Install Lua
        run: |
          echo '::group::apt update'
          sudo apt-get -qq update
          echo '::endgroup::'
          echo '::group::apt install lua 5.1'
          sudo apt-get install -qq lua5.1
          echo '::endgroup::'

      - name: Generate changelog
        run: |
          lua utils/changelog > CHANGELOG.md

      - name: Package and release
        uses: BigWigsMods/packager@cd13fb1
        with:
          args: -d
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
